CREATE TABLE ALL_TIME_BATSMEN
(
	POSITION NUMBER(3),
	PLAYER VARCHAR(20),
	TEAM VARCHAR(20),
	INNINGS NUMBER(4),
	RUNS NUMBER(5),
	AVERAGE NUMBER(3,2),
	STRIKE_RATE NUMBER(3,2),
	HUNDREDS NUMBER(3),
	FIFTIES NUMBER(3),
	HIGH_SCORE NUMBER(4)
);


CREATE TABLE ALL_TIME_BOWLERS
(
	POSITION NUMBER(2),	
	PLAYER VARCHAR(20),
	TEAM VARCHAR(20),
	INNINGS NUMBER(4),
	WICKETS NUMBER(4),
	AVERAGE NUMBER(4,2),
	ECONOMY NUMBER(4,2),
	STRIKE_RATE NUMBER(4,2),
	FOUR_HAUL NUMBER(4),
	FIVE_HAUL NUMBER(4)
);

CREATE TABLE ORANGE_CAP
(
     POSITION NUMBER,
     PLAYER VARCHAR(20),
     TEAM VARCHAR(20),
     INNINGS NUMBER(3),
     RUNS NUMBER(3),
     AVERAGE NUMBER(5,2),
     STRIKE_RATE NUMBER(5,2),
     HUNDREDS NUMBER(3),
     FIFTIES NUMBER(3),
     HIGH_SCORE NUMBER(3)
);

CREATE TABLE PURPLE_CAP
(
	POSITION NUMBER,
	PLAYER VARCHAR(20),
	TEAM VARCHAR(20),
	INNINGS NUMBER,
	WICKETS NUMBER,
	AVERAGE NUMBER(4,2),
	ECONOMY NUMBER(3,2),
	STRIKE_RATE NUMBER(4,2),
	FOUR_HAUL NUMBER,
	FIVE_HAUL NUMBER
);

CREATE TABLE POINTS_TABLE_ALLTIME (
	TEAM VARCHAR(20),
	POINTS NUMBER(3),
	WON NUMBER(3),
	LOST NUMBER(3),
	WINPERCENT NUMBER(5,2)
);

CREATE TABLE TEAMROSTER
(
	TEAM VARCHAR(20), 
	PLAYER VARCHAR(30), 
	MATCHES NUMBER, 
	RUNS NUMBER, 
	WICKETS NUMBER 
);

